@baseUrl = http://localhost:3333

# @name create-account
POST {{baseUrl}}/users 
Content-Type: application/json

{
  "name": "Leonan",
  "email": "leonanorth3@acme.com",
  "password": "123456"
}

### @name authenticate-with-password
POST {{baseUrl}}/sessions/password 
Content-Type: application/json

{
  "email": "leonanorth3@acme.com",
  "password": "123456"
}

### @name authenticate
GET {{baseUrl}}/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTU5YzU0MC03NDMzLTQzOTEtODc5Zi0xMDIzZDhhODU1OWQiLCJpYXQiOjE3MTc0Nzc3MTEsImV4cCI6MTcxODA4MjUxMX0.V1huLVnf5ibi-UID5TSa1Xbg85s4k9fK0WG-jpsg8fY

### @name request-password-recover
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
  "email": "leonanorth3@acme.com"
}

### @name autheticate-with-github
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": "4261e01beec254ab9f09"
}

### @name reset-password
POST {{baseUrl}}/password/reset
Content-Type: application/json

{
  "code": "563a126f-cc2d-457f-9607-677ae35d527b",
  "password": "654321"
} 

# ORGS

### @name create-organization
POST {{baseUrl}}/organization
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4YmM4MDBiZC1hYzNhLTQwNzItODJhMS0zY2M4NjUzY2QzZjQiLCJpYXQiOjE3MTgwNzcyNTksImV4cCI6MTcxODY4MjA1OX0.Jzd9DYKGaLHVeUwA88wnsJZTs88hoqIYEfY7Ir9m2K0

{
  "name": "Rocketseat",
  "domain": "rocketseat.team",
  "shouldAttachUsersByDomain": true
}
